### ISSUE TITLE
HTML syntax: improve script tag auto completion

### ISSUE THREAD

**Issue by FichteFoll** [SublimeTextIssues/DefaultPackages#156]
_From @OliverJAsh on October 1, 2015 13:11_

When I type `<script` then press tab to auto complete, I end up with `<script type="text/javascript"></script>`. `type="text/javascript"` is not needed, so every time I have to delete it.

Could we just auto complete to `<script></script>`?

_Copied from original issue: SublimeTextIssues/Core#1008_

**Comment by FichteFoll** [comment]
For the time being, you could define a snippet that triggers on "script" and completes to the plain `script>$0</script>` (note the missing `<`). Snippets take precedence over completions if the prefix matches exactly.

**Comment by wbond** [comment]
Since the `<script>` tag can be used for types other than JavaScript, and since I don't want to break existing users' workflows, I did the following:

I added a `$2` tab trigger to the completion. When completing `<script>` the normal `type="text/javascript"` attribute will still be included.

For users that want to change the `type` to something different, they can start typing then hit tab *twice* to go onto the contents.

For users who want no attribute, they will complete, hit tab to select the full `type=""` attribute, hit backspace, hit tab again to go onto the contents.

https://github.com/sublimehq/Packages/commit/8cd729f3a6736b697a2d61e70f474a30ba15589f
