### ISSUE TITLE
.c files have C++ syntax highlighting instead of C syntax highlighting

### ISSUE THREAD

**Issue by titoBouzout** [SublimeTextIssues/DefaultPackages#16]
_From @glang on September 18, 2014 14:2_

This is for Build 3065

_Copied from original issue: SublimeTextBugs/Issues#484_

**Comment by wbond** [comment]
The uppercase `C` extension is commonly associated with C++, whereas lowercase `c` with C. From my testing on OS X, Sublime Text can properly distinguish between the two.

It may be that working on a case insensitive filesystem, or just out of convention you run into issues where some C files are using an uppercase extension. In that case the *View > Syntax > Open all with current extension as…* menu can be used to associated the uppercase `C` extension with the C syntax.

**Comment by dnicolson** [comment]
Unfortunately this is due to a macOS limitation, even on case-sensitive file systems `c` and `C` file extensions are considered the same. Apple confirmed this has been the case since 1984.

<img width="639" alt="Screenshot 2019-05-10 at 10 04 16" src="https://user-images.githubusercontent.com/2276355/57586228-34030980-74f3-11e9-8e32-6ef04611a767.png">

Since Apple is unlikely to change this, I would suggest removing the `C` type so that at least C files can be identified properly. For both file extensions Xcode uses "C Source" for the kind.
