### ISSUE TITLE
Default html syntax highlighting incorrect for script tag

### ISSUE THREAD

**Issue by AlekseyMalyshev** [SublimeTextIssues/DefaultPackages#165]
Default html package highlights entire line that contains a script tag. I believe it should highlight only what is in between the tags. I.e., embedded JavaScript code.

![2b5ba0d4-9b0e-11e5-9732-0fc976550321](https://cloud.githubusercontent.com/assets/739471/11797229/98ac4906-a2d2-11e5-9791-9348b7ced7c6.png)

Also I think that this incorrect parsing creates a problem described here:

https://github.com/SublimeTextIssues/Core/issues/43

I think the problem is that when choosing what type of comment ST3 should insert, it uses the information from html parser.

**Comment by FichteFoll** [comment]
You're right in that this issue is related and also partly responsible for the problem in SublimeTextIssues/Core#43, but only partly. I mentioned both of the responsible faults [in my first comment](https://github.com/SublimeTextIssues/Core/issues/43#issuecomment-17951761), which is now split in two thanks to this issue. Which is good, don't get me wrong.

**Comment by FichteFoll** [comment]
This has been fixed partly in that the `source.js` scope is now only applied starting after `<script` and ending before `</script>`. The `src="...">` part is still being marked as source.js however.

**Comment by AlekseyMalyshev** [comment]
Yes, I can see it in the latest version. Thanks!

**Comment by FichteFoll** [comment]
Should be resolved via https://github.com/sublimehq/Packages/commit/d056ca685c90dfd0a8f55e1e76b52695c2ea043b. Will likely be shipped in 3108.

**Comment by wbond** [comment]
This was fixed back in 3108
