### ISSUE TITLE
"<<!DOCTYPE" generation after "<ht..." : incorrect generation

### ISSUE THREAD

**Issue by coucout** [SublimeTextIssues/DefaultPackages#180]
In a new ".html" file, when i type "<b>&lt;ht...</b>" then I hit Enter or TAB, it generates an html document snippet : it's very good.
But there's an aditionnal "<b>&lt;</b>" at the beginning which cause an error, like this:
<b>&lt;</b>&lt;!DOCTYPE html>

**Comment by FichteFoll** [comment]
How about just typing `html`, because that's the snippet's tab trigger?

**Comment by wbond** [comment]
This is fixed by https://github.com/sublimehq/Packages/commit/9a82be41c4e3e03c5c6bf1b0a69dc426f9d9f8c0 and https://github.com/sublimehq/Packages/commit/8e80d82b5807c2b1362d743c8d6489cd41dbde68.

Please note that there will be a copy of the old snippet showing up in your completions list until the next dev build (or beta if you are on that channel) is released. This is because recently we moved all snippets into subfolders, so these modified snippets will not be overriding the ones that are part of the default packages with your current version of Sublime Text.
