### ISSUE TITLE
JavaScript: syntax highlighting breaking after escaped string

### ISSUE THREAD

**Issue by FlamingTempura** [SublimeTextIssues/DefaultPackages#181]
If a string contains an escaped single quote followed by a colon, the remainder of the file is incorrectly highlighted. For example:
```js
var a = '\'.'; // this works
var b = '\':'; // this doesn't work
console.log('blah blah', a); // highlighting broken
var c = function () {};
var d = {
	a: 1,
	b: 2 // highlighting back to normal
};
var e = function () {};
return a;
```

appears in Sublime Text 3 as:
![image](https://cloud.githubusercontent.com/assets/1085434/13534065/4347108e-e22b-11e5-980c-6138a6d7dba4.png)

It appears to got back to normal following an object declaration.

Build 3103, Ubuntu 14.04

**Comment by MattDMo** [comment]
There has been a great deal of work on the JavaScript syntax since the release of 3103. To test the current version, copy the contents of the [current `JavaScript.sublime-syntax`](https://raw.githubusercontent.com/sublimehq/Packages/master/JavaScript/JavaScript.sublime-syntax) to a new view in Sublime, then save the file as `Packages/JavaScript/JavaScript.sublime-syntax` where `Packages` is `~/.config/sublime-text-3/Packages` on Linux, which I assume you're using. You'll have to create the `JavaScript` folder manually.

Once done, the highlighting *should* correct itself automagically. If not, close and reopen the view. It should now look like this (using my [Neon Color Scheme](https://packagecontrol.io/packages/Neon%20Color%20Scheme)):

<img width="441" alt="Neon" src="https://cloud.githubusercontent.com/assets/1776358/13534559/c2f41e94-e203-11e5-8948-632aacb63aa0.png">

or with the default Monokai color scheme:

<img width="440" alt="Monokai" src="https://cloud.githubusercontent.com/assets/1776358/13534511/8a07f5d8-e203-11e5-8f09-5f98b812a0fe.png">

**Comment by FlamingTempura** [comment]
That fixed it, thanks!
